development:
  adapter: postgresql
  encoding: unicode
  database: startpage_development
  pool: 5
  username: travissingleton
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: startpage_test
  pool: 5
  username: travissingleton
  password: 